#!/bin/sh
versionLineNumber=`( grep -n "version =" build.gradle | cut -d' ' -f1 | sed 's/^\(..\).*/\1/')`
lineCommit=`(git log  -L $versionLineNumber,$versionLineNumber:build.gradle --max-count=1 --pretty=format:"%H" | head -n 1)`
currentBranch=`git branch | sed -n '/\* /s///p'`
git cherry -v origin/$currentBranch | cut -d' ' -f2 | tee localCommits.txt
if [ `grep $lineCommit localCommits.txt`  ]; then
        rm -rf localCommits.txt
        exit 0;
        else
        echo "Please update bahmni-mart build version with every git push to master branch"
        rm -rf localCommits.txt
        exit 1;
fi
