apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
data:
  MART_DB_HOST: {{ .Values.secrets.MART_DB_HOST | b64enc | quote }}
  MART_DB_USERNAME: {{ .Values.secrets.MART_DB_USERNAME | b64enc | quote }}
  MART_DB_PASSWORD: {{ .Values.secrets.MART_DB_PASSWORD | b64enc | quote }}
  OPENMRS_DB_HOST: {{ .Values.secrets.OPENMRS_DB_HOST | b64enc | quote }}
  OPENMRS_DB_USERNAME: {{ .Values.secrets.OPENMRS_DB_USERNAME | b64enc | quote }}
  OPENMRS_DB_PASSWORD: {{ .Values.secrets.OPENMRS_DB_PASSWORD | b64enc | quote }}
