name: Validate_PR
on:
  push:
    branches: 
      - master

jobs:
  
  Trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Trivy Scan
        run: ./.github/trivy_scan.sh

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: Trivy
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          